vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        avatar_file:
            uri_prefix: /images/pictures
            upload_destination: '%upload_directory%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        wine_file:
            uri_prefix: /images/pictures
            upload_destination: '%upload_directory%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer