<?php
const WINE = [
  [
    "domaine" => "château de sales",
    "description" => "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. ",
    "comment" => "Lorem Ipsum is therefore always free ",
    "rank" => 3.0,
    "price" => 7.5,
    "stock" => 6,
    "value" => 10.0,
    "cellarLocation" => "A-24",
    "picture" => "",
    "drinkBefore" => 2024,
    "vintage" => 2014,
    "purchaseDate" => "2018-01-28",
    "color" => "rouge",
    "country" => "France",
    "region" => "bordelais",
    "appellation" => "pomerol",
    "type" => "sec",
  ],
  [
    "domaine" => "clos saint apollo",
    "description" => "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. ",
    "comment" => "Lorem Ipsum is therefore always free ",
    "rank" => 3.0,
    "price" => 15.0,
    "stock" => 3,
    "value" => 20.0,
    "cellarLocation" => "B-10",
    "picture" => "",
    "drinkBefore" => 2030,
    "vintage" => 2015,
    "purchaseDate" => "2018-01-28",
    "color" => "blanc",
    "country" => "France",
    "region" => "alsace",
    "appellation" => "gewurztraminer",
    "type" => "sec",
  ],
  [
    "domaine" => "château giscours",
    "description" => "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. ",
    "comment" => "Lorem Ipsum is therefore always free ",
    "rank" => 5.0,
    "price" => 13.0,
    "stock" => 12,
    "value" => 30.0,
    "cellarLocation" => "C-10",
    "picture" => "",
    "drinkBefore" => 2026,
    "vintage" => 2006,
    "purchaseDate" => "2018-01-28",
    "color" => "rouge",
    "country" => "France",
    "region" => "bordelais",
    "appellation" => "margaux",
    "type" => "sec",
  ],
  [
    "domaine" => "château cantenac",
    "description" => "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. ",
    "comment" => "Lorem Ipsum is therefore always free ",
    "rank" => 4.0,
    "price" => 4.3,
    "stock" => 2,
    "value" => 10.0,
    "cellarLocation" => "D-01",
    "picture" => "",
    "drinkBefore" => 2030,
    "vintage" => 2010,
    "purchaseDate" => "2018-01-28",
    "color" => "rouge",
    "country" => "France",
    "region" => "bordelais",
    "appellation" => "margaux",
    "type" => "sec",
  ],
  [
    "domaine" => "château lagune",
    "description" => "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. ",
    "comment" => "Lorem Ipsum is therefore always free ",
    "rank" => 5.0,
    "price" => 7.1,
    "stock" => 10,
    "value" => 12.0,
    "cellarLocation" => "D-02",
    "picture" => "",
    "drinkBefore" => 2025,
    "vintage" => 2012,
    "purchaseDate" => "2018-01-28",
    "color" => "rosé",
    "country" => "France",
    "region" => "bordelais",
    "appellation" => "haut-médoc",
    "type" => "sec",
  ],
  [
    "domaine" => "château duhars",
    "description" => "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. ",
    "comment" => "Lorem Ipsum is therefore always free ",
    "rank" => 5.0,
    "price" => 9.0,
    "stock" => 4,
    "value" => 15.0,
    "cellarLocation" => "D-03",
    "picture" => "",
    "drinkBefore" => 2035,
    "vintage" => 2019,
    "purchaseDate" => "2018-01-28",
    "color" => "rosé",
    "country" => "France",
    "region" => "bordelais",
    "appellation" => "pauillac",
    "type" => "sec",
  ],
  [
    "domaine" => "Jean & Lys Dru",
    "description" => "Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.",
    "comment" => "Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary.",
    "rank" => 5.0,
    "price" => 22.0,
    "stock" => 2,
    "value" => 30.0,
    "cellarLocation" => "D-04",
    "picture" => "",
    "drinkBefore" => 2022,
    "vintage" => 2000,
    "purchaseDate" => "2022-11-08",
    "color" => "blanc",
    "country" => "France",
    "region" => "bourgogne",
    "appellation" => "chablis",
    "type" => "sec",
  ],
  [
    "domaine" => "Hansel Baerysis",
    "description" => "The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. ",
    "comment" => "The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using.",
    "rank" => 4.0,
    "price" => 12.0,
    "stock" => 5,
    "value" => 12.0,
    "cellarLocation" => "A-05",
    "picture" => "",
    "drinkBefore" => 2020,
    "vintage" => 2015,
    "purchaseDate" => "2022-11-02",
    "color" => "blanc",
    "country" => "France",
    "region" => "alsace",
    "appellation" => "riesling",
    "type" => "blanc",
  ],
  [
    "domaine" => "domaine Ducreux",
    "description" => "Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    "comment" => "Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus.",
    "rank" => 0.0,
    "price" => 22.0,
    "stock" => 5,
    "value" => 32.0,
    "cellarLocation" => "K-10",
    "picture" => "",
    "drinkBefore" => 2022,
    "vintage" => 2002,
    "purchaseDate" => "2022-11-01",
    "color" => "rouge",
    "country" => "France",
    "region" => "bordelais",
    "appellation" => "margaux",
    "type" => "sec",
  ],
  [
    "domaine" => "clos maraîcher",
    "description" => "Du volume et de la rondeur par la roussanne, apportant fraîcheur et arômes délicats de pêche de vigne et de poire. \u00c0 la dégustation, l'attaque est franche et très bien équilibrée avec cette belle fraîcheur très caractéristique des vins de la maison. ",
    "comment" => "J'AIME BEAUCOUP miam",
    "rank" => 5.0,
    "price" => 12.0,
    "stock" => 2,
    "value" => 12.0,
    "cellarLocation" => "B_C04",
    "picture" => "",
    "drinkBefore" => 2022,
    "vintage" => 2014,
    "purchaseDate" => "2022-11-03",
    "color" => "rosé",
    "country" => "France",
    "region" => "bourgogne",
    "appellation" => "arbois",
    "type" => "sec",
  ],
  [
    "domaine" => "villa blanche",
    "description" => "Avec ses notes d'abricot, de pêche de vigne et ses subtiles notes boisées grâce à un élevage de 3 mois en f\u00fbt de chêne, ce vin blanc du Languedoc-Roussillon se montre particulièrement accessible et fédérateur dès l'apéritif.",
    "comment" => "Cépage chardonnay. Vin très léger.",
    "rank" => 5.0,
    "price" => 12.0,
    "stock" => 2,
    "value" => 12.0,
    "cellarLocation" => "A-10",
    "picture" => "",
    "drinkBefore" => 2015,
    "vintage" => 2012,
    "purchaseDate" => "2022-11-01",
    "color" => "rosé",
    "country" => "France",
    "region" => "sud-ouest",
    "appellation" => "rivesaltes",
    "type" => "sec",
  ]

];
